add polyfill of Object.values
JakeChampion/polyfill-service pull request #1082
Opened 2017-02-04 08:18 UTC by JounQin

2017-02-04 08:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Financial-Times/polyfill-service?pullRequest=1082) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Financial-Times/polyfill-service?pullRequest=1082) before we can accept your contribution.<br/>

2017-02-09 19:12 UTC, triblondon requested changes
The property this adds is enumerable, but the native version is not. Would it be better to use `Object.defineProperty` to create this property with the correct descriptor?

![image](https://cloud.githubusercontent.com/assets/1735391/22798910/d69ca5ac-eed1-11e6-9d54-61c805a63fed.png)

2017-03-17 05:41 UTC, triblondon commented
@JounQin Are you able to finish off this PR and help us get it merged into the project?

2017-03-17 06:32 UTC, JounQin commented
@triblondon 
Sorry, I was a little busy there days, and just forgot to do that.
I've fixed it just now.

2017-03-17 12:50 UTC, JakeChampion approved these changes

2017-03-17 12:50 UTC, JakeChampion commented
@triblondon, this is ready for another review :-)

2017-03-20 06:59 UTC, triblondon submitted a review, later dismissed
Thanks @JounQin.  Just one bug you need to fix and then I'm happy with it.  Jake and I need to look at aliases more generally but I'm happy for it to not block this PR.

2017-03-20 06:59 UTC, triblondon commented on polyfills/Object/values/config.json
> +		"es2017"
Is ES2017 technically ES8?  I'm losing track.  We currently have a lot of polyfills aliased to `es6`, but not many attached to the year-based names and none attached to `es7` or `es8`.  We might need some policy here, @JakeChampion - thoughts?

2017-03-20 06:59 UTC, triblondon commented on polyfills/Object/values/polyfill.js
> +		enumerate: false,
`enumerate` is not a valid object descriptor property.  Should be [`enumerable`](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty#Description).  It is already false by default, but technically required, so we should include it.

2017-03-20 06:59 UTC, triblondon commented on polyfills/Object/values/polyfill.js
> +		value: values,
You could inline the function anonymously here to avoid creating the overhead of an additional symbol.

2017-03-20 08:12 UTC, JounQin commented on polyfills/Object/values/config.json
> +		"es2017"
Actually I just copy the `config.json` from [Object.entries](https://github.com/Financial-Times/polyfill-service/blob/master/polyfills/Object/entries/config.json).

2017-03-20 14:30 UTC, merged