Optimize the size tracking operations in the Map/Set polyfills
JakeChampion/polyfill-service pull request #1157
Opened 2017-03-30 21:50 UTC by dcherman

The size will be tracked on a per operation basis rather than being
calculated in a getter which changes this from an O(n) operation to O(1)

fixes #1153

2017-03-30 21:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Financial-Times/polyfill-service?pullRequest=1157) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Financial-Times/polyfill-service?pullRequest=1157) before we can accept your contribution.<br/><hr/>**Daniel Herman** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Financial-Times/polyfill-service?pullRequest=1157) it.</sub>

2017-03-31 09:26 UTC, JakeChampion commented
Thanks for the contribution @dcherman, this will definitely help on some large Sets and Maps!

Would you be able to add the email address used for this commit to your account, then reading our [Contributor License Agreement](https://cla-assistant.io/Financial-Times/polyfill-service?pullRequest=1157) and signing it if you are happy with the terms.

2017-03-31 14:21 UTC, dcherman commented
@JakeChampion Will do; waiting to hear back from our legal dept before I can officially sign.  I've read over it and don't expect any roadblocks though, so that should hopefully happen shortly.

2017-04-05 14:45 UTC, dcherman commented
@JakeChampion Sorry for the delay, I've both signed the CLA and added that email address to my account

2017-05-19 12:59 UTC, JakeChampion approved these changes

2017-05-19 13:03 UTC, leggsimon approved these changes

2017-05-19 13:32 UTC, JakeChampion commented
@dcherman This is failing on CI, would you be able to look into this at all?

```
Failures:
 - ie/8:
    -> Map
       http://127.0.0.1:3000/test/tests?mode=targeted&feature=Map
    -> Set
       http://127.0.0.1:3000/test/tests?mode=targeted&feature=Set
 - ie/7:
    -> Map
       http://127.0.0.1:3000/test/tests?mode=targeted&feature=Map
    -> Set
       http://127.0.0.1:3000/test/tests?mode=targeted&feature=Set
```

2017-05-19 13:32 UTC, JakeChampion requested changes
Currently failing on IE7 and IE8

2017-05-19 20:49 UTC, dcherman commented
@JakeChampion Ah, I see the problem.  Need to set `size` in the constructor as well since `Object.defineProperty` isn't supported in IE8, so it was never defined until an operation occurred.  Pushing a fix in a moment.

2017-05-20 12:38 UTC, JakeChampion approved these changes

2017-05-20 12:38 UTC, merged

2017-06-16 09:19 UTC, JakeChampion commented
Hi @dcherman , this is now available for testing on https://qa.polyfill.io/ 👍