using existing polyfills
JakeChampion/polyfill-service pull request #1246
Opened 2017-07-29 07:28 UTC by caub

2017-07-29 07:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Financial-Times/polyfill-service?pullRequest=1246) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Financial-Times/polyfill-service?pullRequest=1246) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Financial-Times/polyfill-service?pullRequest=1246) it.</sub>

2017-08-07 10:53 UTC, JakeChampion requested changes
Need to recommit package lock file and not ignore it

2017-08-07 10:53 UTC, JakeChampion commented on .npmignore
> +package-lock.json
Please could you not ignore the package lock file, this is a very important file to keep for this project as it ensures we pull in the exact versions of third party polyfills that we have tested on BrowserStack

2017-08-07 10:54 UTC, JakeChampion commented
@caub I'm not sure what using third party polyfills gain us for these features as the polyfill code for them is small. Could you explain the reasoning behind this please

2017-08-07 10:59 UTC, caub commented
it was just a suggestion, this polyfill is the main one for Object.entries/values, it's well supported probably like the one you did, but it saves time and worry to rely on it probably

if you don't want it's ok, I can understand, it makes sense too

2017-09-01 14:08 UTC, JakeChampion commented
I'm going to close this PR as we already have polyfills for these features, thanks for taking the time to create it and sorry it didn't get merged.

2017-09-01 14:08 UTC, closed without merging