Disable request logging when NODE_ENV set to production
JakeChampion/polyfill-service pull request #2658
Opened 2021-12-21 10:54 UTC by Menci

Currently even if I set `NODE_ENV` to `production`, it logs each request. I think it's unnecessary.

2021-12-21 10:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Financial-Times/polyfill-service?pullRequest=2658) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Financial-Times/polyfill-service?pullRequest=2658) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Financial-Times/polyfill-service?pullRequest=2658) it.</sub>

2021-12-21 11:59 UTC, JakeChampion requested changes
Hi @Menci - Could you change the code to only set `requestLogFormat` to null if another environment variable is set and not use NODE_ENV, for example we could use `process.env.DISABLE_REQUEST_LOGGING` instead as that is more explicit in it's intent

E.G. Something like:
```js
const options = {
...
};

if (process.env.DISABLE_REQUEST_LOGGING) {
    options.requestLogFormat = null;
}
```

2021-12-22 10:39 UTC, JakeChampion approved these changes

2021-12-22 11:52 UTC, Menci commented
The CI checks failed since `npm ci` errors. Could you please re-run the checks?

2021-12-22 16:37 UTC, merged