Upgrade polyfill-library to 3.111.0
JakeChampion/polyfill-service pull request #2674
Opened 2022-03-25 10:47 UTC by jdeniau

2022-03-25 10:49 UTC, JakeChampion commented on server/routes/v3/polyfill.js
> +const polyfillio_3_110_1 = require("polyfill-library-3.110.1");
This new variable will need to be added into the array on line 104 of this file 👍

2022-03-25 10:50 UTC, JakeChampion requested changes
Thanks for much for this @jdeniau, there is one blocking change which will need to be done before this can be merged and released 👍 

https://github.com/Financial-Times/polyfill-service/pull/2674/files#r835157065

2022-03-25 10:52 UTC, jdeniau commented on server/routes/v3/polyfill.js
> +const polyfillio_3_110_1 = require("polyfill-library-3.110.1");
Done. 
It seems that sometime the older version is not set in the files so I tried to add 3.110.1 everywhere, but I don't know if it is really expected ¯\_(ツ)_/¯

2022-03-25 10:57 UTC, JakeChampion approved these changes

2022-03-25 10:58 UTC, JakeChampion commented on server/routes/v3/polyfill.js
> +const polyfillio_3_110_1 = require("polyfill-library-3.110.1");
That would have been an error from me 😔 thank you for finding and fixing all those

2022-03-25 18:03 UTC, merged

2022-04-01 13:32 UTC, jdeniau commented
@JakeChampion Is there something that I can do to release this onto the cdn ? 🤔 (It seems that is still the 3.110.1 in production)

2022-04-01 13:36 UTC, JakeChampion commented
> @JakeChampion Is there something that I can do to release this onto the cdn ? 🤔 (It seems that is still the 3.110.1 in production)

I've started the process to release this to production now 👍