polyfill symbol in BlackBerry
JakeChampion/polyfill-service pull request #918
Opened 2016-10-04 11:13 UTC by wheresrhys

@JakeChampion being deliberately conservative with versions given the compatibility problems we've had with symbol before. FT only needs v10 covered. If others want to invest time in verifying Symbol and related polyfills don't blow up in BB<10 then config can be modified in future PRs

2016-10-04 12:41 UTC, JakeChampion commented
@wheresrhys Do you have screenshots of the tests passing on BB10?

2016-10-04 12:47 UTC, wheresrhys commented
not of the tests, but ft.com is fixed by forcing `Array.from` and `Map` to be bundled on BB10, which is reasonable evidence that this is ok. I'll work on running the tests this afternoon though

2016-10-04 15:01 UTC, JakeChampion requested changes

2016-10-04 15:01 UTC, JakeChampion commented on polyfills/Array/from/config.json
> +		"bb": ">=10"
I think this needs to be `10 - *` to be valid semver.

2016-10-04 16:00 UTC, wheresrhys commented
https://mail.google.com/mail/u/0?ui=2&ik=072fc90e6a&attid=0.1&th=1579069e5bc84b13&view=fimg&disp=thd&attbid=ANGjdJ8nTt0JZiou59_R_PeeH-kVedI021rUQWUkW6TK58XMsXEeZ2q3x931i4qpf_ZDuJ9AG_uCgRKshnIqAPaUY6foObEvYf9UL0uoJu01pQXyr4iX5_31rjTHTLI&ats=2524608000000&sz=w2460-h1360

2016-10-04 16:00 UTC, JakeChampion approved these changes

2016-10-04 16:27 UTC, merged

2016-10-10 16:22 UTC, JakeChampion commented
@wheresrhys This is now live on http://qa.polyfill.io - would you be able to report back whether we have fixed your issue?