Add polyfill for pre-ES6 form of `Function.name`
JakeChampion/polyfill-service pull request #951
Opened 2016-10-24 10:43 UTC by JamesMGreene

Fixes #943 
Closes JamesMGreene/Function.name#3

2016-10-25 06:06 UTC, triblondon reviewed
Hi @JamesMGreene, thanks for this.  Could you check off all the points in this list:

https://polyfill.io/v2/docs/contributing/common-scenarios#adding-browsers

To help us merge this ASAP?

2016-10-25 06:07 UTC, triblondon commented
Pushed to a local branch for CI

2016-10-25 06:20 UTC, falsandtru requested changes

2016-10-25 06:20 UTC, falsandtru commented on polyfills/Function/name/tests.js
> +	proclaim.equal(anon.name, '');
In latest chrome, `anon.name` is `'anon'`, not an empty string.

2016-10-25 06:27 UTC, triblondon commented on polyfills/Function/name/tests.js
> +	proclaim.equal(anon.name, '');
Agreed:

![image](https://cloud.githubusercontent.com/assets/1735391/19675110/80d35d90-9ac7-11e6-8cd5-b288b5d6bd53.png)

2016-10-25 06:33 UTC, falsandtru commented
@triblondon As I commented, some tests fail on the latest browsers. So we need to run tests on them. Can you add the target browsers such as Chrome latest(53+), Chrome canary, and Android 5+?

2016-10-25 09:24 UTC, triblondon commented
@falsandtru https://github.com/Financial-Times/polyfill-service/pull/954

2016-10-25 10:36 UTC, JamesMGreene commented
> Check reliable sources of browser support information, e.g. MDN, caniuse and Kangax. Tell us what these sources say about the browser/polyfill combo that you want to add or remove, and link to the relevant pages from your PR.

 - [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/name)
 - [MDN - Browser Compatibility](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/name#Browser_compatibility)
 - [caniuse](http://kangax.github.io/compat-table/es6/#test-function_name_property) (for the enhanced ES6 form, though)

**Basic support**
 - Chrome 33.0
 - Firefox (Yes)
 - IE 12
 - Opera (Yes)
 - Safari (Yes)


> Explain how you have tested support (or lack of) in the browser concerned. Ideally, include a screenshot of the relevant browser running our test suite for that feature.

Ran the newly added tests against my own SauceLabs account with `grunt ci`.

> State your agreement to our contribution terms.

I agree to the contribution terms.

2016-10-25 11:24 UTC, JamesMGreene commented
@triblondon FYI, I rebased your changes from `master` into the PR branch now, so the merge commit no longer shows up.

2016-10-26 01:00 UTC, triblondon approved these changes
Outstanding.

2016-10-26 01:03 UTC, triblondon commented
Pushed to local branch for CI.  Note to self: because it was rebased I had to force push.

2016-10-26 08:36 UTC, merged

2016-10-26 18:00 UTC, JamesMGreene commented
:+1: 💝

2016-10-26 20:57 UTC, JakeChampion commented
Thanks for the contribution @JamesMGreene! Did you know we offer one month's free premium access to all FT content (normally $50) to anyone who has a pull request merged in this repository? If you want to claim it, there's [one Google form](https://docs.google.com/a/ft.com/forms/d/1aykPiYBwqKpKY6nvGVi43wOU_5epr3XLgE00Vi52SMQ/viewform) to fill out :-)